package com.javen.mapping;

import java.util.List;

import com.javen.model.pictureBook;

public interface pictureBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_book
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    int deleteByPrimaryKey(Integer pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_book
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    int insert(pictureBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_book
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    int insertSelective(pictureBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_book
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    pictureBook selectByPrimaryKey(Integer pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_book
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    int updateByPrimaryKeySelective(pictureBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_book
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(pictureBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_book
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    int updateByPrimaryKey(pictureBook record);
    
    List<pictureBook> selectPicture();
}