package com.javen.model;

public class pictureBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_book.picture_id
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    private Integer pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_book.picture_option
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    private String pictureOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_book.picture_show
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    private byte[] pictureShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_book.picture_id
     *
     * @return the value of picture_book.picture_id
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    public Integer getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_book.picture_id
     *
     * @param pictureId the value for picture_book.picture_id
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    public void setPictureId(Integer pictureId) {
        this.pictureId = pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_book.picture_option
     *
     * @return the value of picture_book.picture_option
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    public String getPictureOption() {
        return pictureOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_book.picture_option
     *
     * @param pictureOption the value for picture_book.picture_option
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    public void setPictureOption(String pictureOption) {
        this.pictureOption = pictureOption == null ? null : pictureOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_book.picture_show
     *
     * @return the value of picture_book.picture_show
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    public byte[] getPictureShow() {
        return pictureShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_book.picture_show
     *
     * @param pictureShow the value for picture_book.picture_show
     *
     * @mbggenerated Wed Jan 31 11:34:11 CST 2018
     */
    public void setPictureShow(byte[] pictureShow) {
        this.pictureShow = pictureShow;
    }
}